CREATE TYPE status AS ENUM ('REGISTERED', 'NEW', 'INVALID', 'PROCESSING', 'PROCESSED');
CREATE TYPE action AS ENUM ('PURCHASE', 'WITHDRAW');

CREATE TABLE orders (
    id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users (id),
    number TEXT NOT NULL UNIQUE,
    score FLOAT,
    status status NOT NULL,
    action action NOT NULL,
    ctime TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
